package com.example.liberary.View.Activities

import android.content.Intent
import android.os.Bundle
import android.widget.Button
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.GridLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.example.liberary.*
import com.example.liberary.Adapters.FacultiesAdapter
import com.example.liberary.constants.Constants

class WelcomeActivity : AppCompatActivity() {
    private lateinit var recyclerView:RecyclerView
    private lateinit var adapter:FacultiesAdapter
    private lateinit var majorsIntent : Intent
    private lateinit var faculties:ArrayList<Faculty>

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_welcome)
        recyclerView = findViewById(R.id.faculties_rv)
        supportActionBar?.hide()
        initTheFaculties()
    }

    fun initTheFaculties(){
         faculties = arrayListOf(
             Faculty("Business English",R.drawable.business ,arrayListOf(
             Major("Information Systems", arrayListOf(Course("Principles of Mathematics ", "MATH 101", "This course enables students to broaden their understanding of relationships and extend their problem-solving and algebraic skills through investigation, the effective use of technology, and abstract reasoning.", "1", "https://people.umass.edu/klement/pom/pom.pdf","None"),
                 Course("Financial Mathematics","MATH 201","This course explain basic concepts of financial mathematics with a central focus on discrete models and an aim to demonstrate simple, but widely used, financial derivatives for managing market risks.","2","http://poincare.matf.bg.ac.rs/~kmiljan/UFM.pdf","Math 101"),
                 Course("Mathematical Insurance","MATH 401","This course is intended primarily as a text for courses in the mathematics of life insurance in colleges and universities. It also should prove of interest to readers, other than college students, who wish to understand the fundamentals of life insurance. ","4","http://web.math.ku.dk/~mogens/lifebook.pdf","Math 201, Sts 301"),
                 Course("Descriptive Statistics","STS 201","Descriptive Statistics course,makes the student familiar with the most important statistics used to describing data in a form that is easy to understand.","2","https://cosmologist.info/teaching/STAT/CHAP4.pdf","Math 101"),
                 Course("Applied Statistics","STS 301","The aim of applied statistics course is to make the students familiar with modern techniques and methods essential to most successful managers and decision makers.","3","http://thuvienso.bvu.edu.vn/bitstream/TVDHBRVT/15780/1/Applied-Statistics.pdf","Sts 201"),
                 Course("Advanced Statistics","STS 401","The aim of advanced statistics course is to make the students familiar with different techniques which is essential to most successful decision-makers.","4","http://silver.nitt.edu/~esgopi/pdf/Statisticaltest.pdf","Sts 301"),
                 Course("Introduction of Computer","COMP 102","This course introduce computer hardware,software,procedures,systems,and human resources and explores their integration and application in business and other segments of society.","1","http://web.cse.ohio-state.edu/cse1111/Electronic%20Chapters/Shelly%20Cashman%20Electronic%20File/Intro%20to%20computers/Introduction%20to%20Compters-COM%201.pdf","None"),
                 Course("Principles of Information Systems","INF 201","This course consists of an overview of the various components of a comprehensive information infrastructure including computing platforms,software architectures,and telecommunications networks.","2","http://site.iugaza.edu.ps/kdahleez/files/2014/09/stair78292_0538478292_02.01_chapter01.pdf","COMP 102"),
                 Course("Principles of Programs Planning","INF 301","This course presents object-oriented and procedural software engineering methodologies in data definition and measurement, abstract data type construction,and use in developing screens,reports,and other IS applications problems .","3","http://staff.um.edu.mt/__data/assets/pdf_file/0010/57169/jn.pdf","INF 201"),
                 Course("Basic of Systems Analysis","INF 302","This course offers an overview of the system development life cycle. Discussion of the information gathering and reporting activities and the transition from analysis to design is given","3","https://www.ybmahata.com/download/Sunway_International_College%20/EBOOK_System%20Analysis%20and%20Design/Joseph%20Valacich_%20Joey%20George_Jeff%20Hoffer-Essentials%20of%20Systems%20Analysis%20and%20Design-Prentice%20Hall%20(2014).pdf","INF 201"),
                 Course("Data Base","INF 303","The course provides a general overview of database management systems (DBMS) and emphasizes the development of applications for managerial decision-making . it offers study of concepts,theory,design techniques and retrieval methods,particularly using the industry-standard SQL data language. ","3","https://zcht.home.amu.edu.pl/pliki/Databases%20for%20beginners.pdf","INF 201"),
                 Course("Basics of Systems Design","INF 304","This course provides an introduction to the systems development life cycle,with emphasis on the design phase. structured methodologies utilizing CASE tools, as well as prototyping techniques,are covered.","3","https://ptolemy.berkeley.edu/books/Systems/PtolemyII_DigitalV1_02.pdf","INF 302"),
                 Course("Modern Programing Language","INF 305","This course covers the history,theory, and practice of modern programming languages,with emphasis on markup languages and their associated scripting languages.","3","http://www.halvorsen.blog/documents/programming/python/resources/Python%20Programming.pdf","INF 301") ,
                 Course("Experts Systems and Decision Support System","INF 306","This course covers Decision Support Systems and Experts Systems in roughly equal measure .Issues that integrate the two fields,such as Executive Information Systems are addressed briefly.","3","https://wps.pearsoncustom.com/wps/media/objects/6904/7070226/ISY341_Ch01.pdf","INF 303") ,
                 Course("Information Centers Development","INF 401","This course covers the topics related to the running and maintenance of information center, and describe the different organization charts of information center and the impact on the organization.","4","https://www.knowledgeisle.com/wp-content/uploads/2019/12/2-Aur%C3%A9lien-G%C3%A9ron-Hands-On-Machine-Learning-with-Scikit-Learn-Keras-and-Tensorflow_-Concepts-Tools-and-Techniques-to-Build-Intelligent-Systems-O%E2%80%99Reilly-Media-2019.pdf","INF 201"),
                 Course("Software in Business","INF 402","This course introduces the development of business-oriented application programs, using case studies to stress the principles of good program design. Application software includes, but may not be limited to Microsoft Office.","4","https://www.tutorialspoint.com/cloud_computing/cloud_computing_tutorial.pdf","INF 201"),
                 Course("Management of Information Transfer Networks","INF 403","This course analyzes historical and current developments impacting the evolution of telecommunications. Video,voice and data technologies are studied, including analog, digital, satellite, and wireless communications. ","4","https://ncert.nic.in/textbook/pdf/lecs110.pdf","INF 201"),
                 Course("Systems Analysis & Design","INF 404","This course provides a survey of human-computer interaction and of all facts human factors relevant to the design, development, and use of Information Systems.It describes the contributions of information systems, computer science, psychology, sociology, and engineering to human-computer interaction.","4","https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf","INF 304"),
                 Course("DataBases Systems Problems","INF 405","The course offers hands-on experience for developing client/server database applications using a major database management system. Students learn how to create and manipulate database objects including tables, views, and sequences;develop program units using SQL; and implement client applications such as forms and reports.","4","https://www.hcoe.edu.np/uploads/attachments/r96oytechsacgzi4.pdf","INF 303"),
                 Course("Medical Information Systems","INF 406","The focus of this course is on health care information systems in the local area or enterprise environment. Topics include computerized patient records, survey applications in the health care specialties, decision support systems, clinical information system design architectures, and computer-based training for patients and providers. ","4","https://wtf.tw/ref/duckett.pdf","INF 303"),
                 Course("Advanced Study in Operating Systems","INF 407","This course provides coverage of the design and implementation of general purpose multitasking operating systems.","4","https://doc.lagout.org/security/Advanced%20Operating%20Systems%20and%20Kernel%20Applications%20Techniques%20and%20Technologies.pdf","INF 201")))

         , Major("Finance and Investment",arrayListOf(Course("Financial Markets Theory","FIN 301","This course is designed to provide students with concepts and practices of the financial market theory.","3","http://dl.rasabourse.com/Books/Finance%20and%20Financial%20Markets/%5BFrederic_S._Mishkin%5D_Stanley_Eakins_Financial_Markets_and_Institutions%28rasabourse.com%29.pdf","ECO 201"),
                 Course("Securities Intermediates","FIN 302","This course explains the role of money and capital markets,which deals with securities, markets and financial institutions including banks,insurance companies,mutual funds,and investment banking firms ","3","http://dl.rasabourse.com/Shiller.Foundations%20of%20Financial%20Markets%20and%20Institutions.pdf","ACC 202, ECO 201"),
                 Course("Portfolio Management","FIN 303","This course is intended to emphasize on consideration of portfolios rather than of individual securities held by individuals or institutions ","3","http://www.mim.ac.mw/books/Frank%20Reilly's%20Investment%20Analysis%20and%20Portfolio%20Management%20(10th%20Edition).pdf","ACC 202, ECO 201,Math 201"),
                 Course("Monetary & Banking Policies","FIN 304","This course is designed to help students understand the capital market structure, financial policies and techniques ","3","https://ccsuniversity.ac.in/bridge-library/pdf/Eco-International-Finance.pdf","ECO 201,ACC 202,MATH 201"),
                 Course("International Monetary Markets","FIN 305","This course aim to introduce the main concepts of the international monetary funds,analysis and evaluation.","3","https://ccsuniversity.ac.in/bridge-library/pdf/Eco-International-Finance.pdf","ECO 201"),
                 Course("Egyptian Stock Exchange","FIN 306","This course deals with investments in securities quoted on the egyptian stock exchange(ESE),explain the financial investments directly and indirectly bounds and stocks (securities) ","3","https://journals.ekb.eg/article_169612_45e0caf8d810b3b7700faa31b82be49e.pdf","ACC 202,MATH 201,ECO 202"),
                 Course("Investments Banks","FIN 401","This course explains the role of the investment banks and establishing new projects or expanding the existing projects.","4","https://catalogimages.wiley.com/images/db/pdf/9781118615775.excerpt.pdf","FIN 304"),
                 Course("Specialized Banks","FIN 402","The aim of this course is to provide the student with the basic knowledge needed to cover the banking system,banking activities and various kinds of specialized banks","4","https://www.newyorkfed.org/medialibrary/media/research/staff_reports/sr967.pdf","FIN 304"),
                 Course("Credit Management","FIN 403","This course is designed to provide students with concepts and the main principles of credit management It highlights the type of credit and credit policies and financial analysis for granting credits.","4","https://www.bis.org/publ/bcbsc125.pdf","ECO 302"),
                 Course("International Finance","FIN 404","This course deals with the main concepts of international finance, international monetary funds and foreign investment.","4","http://dspace.oneu.edu.ua/jspui/bitstream/123456789/2844/1/International%20finance.pdf","FIN 305"),
                 Course("Operation Research in Finance & Investments","FIN 405","This course is an introduction intended to solve quantitative problems and offers a review of techniques that can be used in quantitative analysis in finance and investment. ","4","http://www.ijmbs.com/41/reshampal.pdf","STS 201"),
                 Course("Quantitative Methods in Stock Exchange","FIN 406","The objective of this course is to highlight how to use the quantitative analysis and techniques to support and enhance decision associated with stock exchange.","4","https://www.hu.edu.eg/wp-content/uploads/2020/11/jfe-8-1-6-1.pdf","FIN 302,FIN 303,FIN 306,STS 201"),
                 Course("Central Banks","FIN 407","This course is an intro to C.B systems, the need for central banks, the C.B functions, the C.B responsibilities","4","https://www.spektro-bi.org/uploader/100217~[Thammarak_Moenjak]_Central_Banking_Theory_and_Pr(b-ok.org)-1.pdf","ECO 302"),
                 Course("Finance and Investments Problems","FIN 408","This course serves as an indicator of the financial system development.","4","https://www.nber.org/system/files/working_papers/w1396/w1396.pdf","ECO 302"),
                 Course("Quantitative Methods in Banks & Portfolio","FIN 409","The objective of this course is to qualify the students in mastering the most useful quantitative and practical techniques that are being used in banks, portfolio and financial markets.","4","https://books.mec.biz/tmp/books/TPMYHLYLPLCGGS6VI726.pdf","FIN 303,STS 201"),
                 Course("Financial Policies for Institutions","FIN 413","This course explains the financial analysis, determining financial needs and requirements","4","https://www.g24.org/wp-content/uploads/2016/01/FINANCIAL-policies.pdf","BUS 304")))

         , Major("Accounting",arrayListOf(Course("Principles of Accounting","ACC 101","This course introduces students to accounting, its concepts and principles. It focuses,however, on the accounting cycle and the preparation of financial statements.","1","https://www.accountingcoach.com/pro-samples/accounting-basics-explanation.pdf","NONE"),
                 Course("Financial Accounting","ACC 102","The objective of this course is to enhance the understanding of the financial statements prepared by the accountants.It covers, in detail , the balance sheet elements including current and non-current assets,liabilities and owner's equity.","1","https://web.ung.edu/media/university-press/Principles-of-Financial-Accounting.pdf?t=1542408454385","ACC 101"),
                 Course("Partnership Accounting","ACC 201","The objective of this course is to provide deep understanding of the nature and features of partnership from business and the application of different accounting assumptions, principles and concepts.","2","http://www.pearsoned.ca/highered/divisions/virtual_tours/lee/sample.pdf","ACC 102"),
                 Course("Corporations Accounting","ACC 202","The objective of this course is to provide deep understanding of accounting issues involved in the formation, operations and liquidation of the corporations.","2","https://www.icsi.edu/media/webmodules/Corporate%20and%20Management%20Accounting.pdf","ACC 102"),
                 Course("Cost Accounting","ACC 301","The objective of this course is to introduce students to cost accounting, cost behaviour,costing methods and overhead allocations.","3","http://cbseacademic.nic.in/web_material/Curriculum/Vocational/2018/Accounting%20and%20Taxation/Cost%20Accounting%20class%20XI.pdf","ACC 102,BUS 103"),
                 Course("Specialized Accounting","ACC 302","This course covers a variety of subjects.Examples of these are divisionalized enterprises","3","https://ncert.nic.in/textbook/pdf/keac101.pdf","ACC 102"),
                 Course("Governmental Accounting & National Accounting","ACC 303","This course is designed to illustrate some fundamental concepts of government and national accounting systems.Government accounting deals with budgeting and its approaches,line item budget,PPBs,PB and ZBB,budgetary control and accounting cycle","3","https://unstats.un.org/unsd/publication/SeriesF/seriesF_85.pdf","ACC 102"),
                 Course("Auditing","ACC 304","An introduction to the basic principles of auditing.(audit reports, audit responsibilities and objectives,audit evidence, internal control and control risk)","3","http://library.wbi.ac.id/repository/211.pdf","ACC 202"),
                 Course("Tax Accounting (1)","ACC 305","The course introduces students to the tax system applied in egypt and its evolution since 1939.","3","https://www.mca.gov.in/Ministry/notification/pdf/AS_22.pdf","ACC 202"),
                 Course("Tax Accounting (2)","ACC 401","It explains the tax on natural person's income and how the students can be prepare the tax declaration and the adjustments made in accounting net profit to be taxable net profit ","4","https://www.mca.gov.in/Ministry/notification/pdf/AS_22.pdf","ACC 202"),
                 Course("Cost Accounting Systems","ACC 402","This course helps the students to understand and learn Break-even analysis and cost volume. profit analysis","4","https://static.careers360.mobi/media/uploads/froala_editor/files/Cost-Accounting-System.pdf","ACC 301"),
                 Course("Operation Research in Accounting","ACC 403","The aim of this course is to provide a complete and modern treatment of basic methodology.","4","http://www.bitsavers.org/pdf/trw/papers/Vazsonyi_Operations_Research_and_the_Accountant_Jun56.pdf","ACC 301"),
                 Course("Financial Institutions Accounting","ACC 404","This course deals with the environment, regulations and accounting treatments of the financial institutions, banking and insurance companies.","4","https://corporatefinanceinstitute.com/assets/cfi-Accounting-eBook.pdf","ACC 202") ,
                 Course("Accounting Information Systems","ACC 405","This course helps the students to understand and learn overview of information systems and accounting, environments of information system,managerial decision-making and information processing, reporting ","4","http://site.iugaza.edu.ps/hmadi/files/2014/11/JAMES-AIS_unprotected.pdf","ACC 202"),
                 Course("Advanced Studies in Auditing","ACC 406","An advanced study of (auditing) topics of significance for a student who has an idea about the basic principles of auditing.","4","https://ebooks.lpude.in/commerce/mcom/term_4/DCOM509_ADVANCED_AUDITING.pdf","ACC 402"),
                 Course("Management Accounting & Budgeting","ACC 408","This course is intended to introduce students to managerial accounting .The course comprises budgeting system,accounting information for decision-making,financial analysis and internal performance evaluation","4","https://kaplanpublishing.co.uk/docs/librariesprovider3/look-inside/aat/professional/management-accounting-budgeting/look-inside-study-text-aat-management-accounting-budgeting.pdf?sfvrsn=ad757e01_2","ACC 301"),
                 Course("International Accounting","Acc 409","This course presents international accounting within the context of the managing multinational enterprises and how it is practiced worldwide.","4","http://digilib.stiem.ac.id:8080/jspui/bitstream/123456789/191/1/International%20Accounting_Choi%20and%20Meek.pdf","ACC 202"),
                 Course("Accounting Problems","ACC 410","The objectives of this course is to study advanced topics in accounting related to department and branches,combinations and consolidation, the accounting concept and problems involved are discussed and solutions are provided.","4","http://www.untag-smd.ac.id/files/Perpustakaan_Digital_1/ACCOUNTING%20Critical%20Financial%20Accounting%20Problems%201567201164.pdf","ACC 301,ACC 304")))
         ,
                 Major("Business Administration", arrayListOf(Course("Principles of Management","BUS 101","Introducing students to the basic knowledge and concepts of management through twofold approach ,first selected contributors of management theory.second management functions and managerial roles ","1","http://www.microlinkcolleges.net/elib/files/undergraduate/Management/Principles%20of%20Management.pdf","NONE"),
                 Course("Managerial Behaviour","BUS 102","An introduction of the field of O.B. it deals with the subjection three levels","1","https://ccsuniversity.ac.in/bridge-library/pdf/Main-Principles%20of%20Management%20and%20Organisational%20Behaviour.pdf","BUS 101"),
                 Course("Production Management","BUS 103","This course intended as an introduction to the field of production and quantitative management ","1","http://www.nitc.ac.in/app/webroot/img/upload/Production%20Management%20Module%201%20Course%20notes.pdf","BUS 101"),
                 Course("Marketing Management","BUS 201","Marketing has its origins in the fact that humans are creatures of needs and wants. Needs and wants create a state of discomfort in people, which is resolved through acquiring products to satisfy these needs and wants. ","2","http://muhasib-az.narod.ru/kitab/menecment/Philip_Kotler_Marketing_Management.pdf","BUS 101"),
                 Course("Purchasing & Warehousing Management","BUS 202","The objective of this curriculum is to provide the students with an up-to- date strategic and practical perspective on purchasing and supply management (PSM). Effective PSM can contribute significantly to the success of most organizations.","3","http://gitamskadapa.org/library/books/mba3sem/SCM/purchasing-and-supply-chain-management.pdf","BUS 101"),
                 Course("public & local Management","BUS 301","This course is designed to introduce the student to the basic concepts of public administration and public sector management. ","3","https://ostromworkshop.indiana.edu/pdf/seriespapers/2017spr-colloq/avellaneda-paper.pdf","BUS 103,BUS 201,BUS 202"),
                 Course("Management Development","BUS 302","The aim of this course is to present a reasonably but complete introduction to the subject of management development. It helps the students to understand and to know how to formulate a scheme of management development through learning","3","https://nscpolteksby.ac.id/ebook/files/Ebook/Business%20Administration/ARMSTRONGS%20HANDBOOK%20OF%20HUMAN%20RESOURCE%20MANAGEMENT%20PRACTICE/45%20-%20Management%20Development.pdf","BUS 103,BUS 201,BUS 202"),
                 Course("Hospital Management","BUS 303","The aim of this course is to present an integrated picture of hospital management as a vital institution in society The various components of hospital management activities are defined and analyzed.","3","https://ncert.nic.in/vocational/pdf/keda101.pdf","BUS 103,BUS 201,BUS 202"),
                 Course("Financial Management & Investment","BUS 304","This course give us An overview of financial management. Analysis of financial statements. Risk and return. Bonds and Stocks and their valuation. The basics of capital budgeting. cash flow estimation, long-term and short-term financing. ","3","https://vcmdrp.tums.ac.ir/files/financial/istgahe_mali/moton_english/financial_management_%5Bwww.accfile.com%5D.pdf","ACC 202,BUS 101,MATH 201"),
                 Course("Specialized Institutions Management","BUS 305","This course takes a comprehensive view of management in specific institutions. It concentrates on hotel management and commercial banks management.","3","http://anucde.info/bba1a.pdf","BUS 103,BUS 201, BUS 202"),
                 Course("Small Business Administration","BUS 306","This course is designed to introduce the students to the field of small business. The course objectives concentrate on the nature of managerial process and examine the reasons to go international and major elements of different culture and the role of Internet in marketing and the student should apply a case study to examine some issues of small business","3","https://sgp.fas.org/crs/misc/RL33243.pdf","BUS 103,BUS 201, BUS 202"),
                 Course("Human Resource Management","BUS 307","This course explain that A firm's human resources are its employees, including both workers and mangers. The human resources may be the most important resource a firm has. Along with planning, organizing, directing and controlling.","3","https://www.sscasc.in/wp-content/uploads/downloads/BBM/Human-Resource-Management.pdf","BUS 102"),
                 Course("Managerial Problems","BUS 401","The course concentrates on managerial problem facing the Egyptian institutions and the influence on local and international environments. In addition, it explains the recent trends and events such as privatization and globalization.","4","https://core.ac.uk/download/pdf/230046319.pdf","BUS 302,BUS 307"),
                 Course("Public Relations","BUS 402","This course has three objectives. First : Explaining the basic theories and principles of public relation. Secondly, supplying the practical information needed to implement public relations activities. ","4","https://www.sjsu.edu/ajeep/docs/IntroToPR.pdf","BUS 201"),
                 Course("Financial Institution Management","BUS 403","This course to capture the major forces that are changing the financial landscape for financial institutions to give students a sense of the dynamic nature of financial markets and institutions and the challenges faced by those who choose a career in institution.","4","http://dl.rasabourse.com/Books/Finance%20and%20Financial%20Markets/%5BSaunders%5DFinancial%20Institutions%20Management%20A%20Risk%20Management%20Approach%28rasabourse.com%29.pdf","BUS 304"),
                 Course("Business Strategies","BUS 404","This course aims to develop an understanding of strategic management concepts, research and theories.","4","https://www.mcgill.ca/economics/files/economics/what_is_business_strategy.pdf","BUS 302,BUS 307"),
                 Course("Management Information Systems","BUS 405","This course aims to introduce the main concepts, principles and techniques of management information systems. Management Information systems (MIS) is computer-based information systems that help to improve the management process and enhance decision-making process","4","https://sctevtservices.nic.in/docs/website/pdf/140304.pdf","INF 201"),
                 Course("Marketing Research & Advertising","BUS 406","The objective of this course is to help the student understand and practices the marketing research skills and help them understand the its concepts and applications in real-life situation.","4","https://www.zamaros.net/Market%20Research.pdf","BUS 201,STS 301"),
                 Course("Communications","BUS 407","This course covers business communication by presenting insights into real-life business situations, It covers the basic principles: Ethics, law. cultural diversity technology, audience centered message, and the writing process. ","4","https://www.uou.ac.in/sites/default/files/slm/BHMAECC-II.pdf","BUS 307"),
                 Course("Operations Research in Management","BUS 408","The purpose of this course is to provide graduate students with a sound conceptual understanding of the role it plays in decision-making process.","4","https://prolightinggroup.com/wp-content/uploads/2020/08/Operations-Research-and-Management-Science-Handbook.pdf","BUS 103,MATH 201,STS 201"),
                 Course("Multinational Corporation Management","BUS 409","The course objective is to help students understand the concepts and theories of international business and be able to analyze the environment and apply the needed modification on organizations functions. ","4","http://www-management.wharton.upenn.edu/guillen/files/mneconcept.pdf","BUS 302,BUS 407")))
         ,
             Major("Economics", arrayListOf(
                 Course("Micro Economics","ECO101","This course provides the student with the main economic problem and the definition of economic science with its main two components: micro- and macro-. ","1","https://www.pfw.edu/dotAsset/142427.pdf","NONE") ,
                 Course("Macro Economics","ECO 102"," his course covers the definitions of macroeconomic variables, Gross National Product. National Income, aggregate demand, aggregate supply.","1","https://homepage.univie.ac.at/robert.kunst/macro1.pdf","ECO 101"),
                 Course("Money and Banking","ECO 201","This course covers the definition and functions of money, different monetary systems and their developments, the role of commercial bank and central banks in affecting the supply of money and credit in the Egyptian economy.","2","https://my.uopeople.edu/pluginfile.php/57436/mod_book/chapter/37370/book.wrightmoneybanking.optimized.complete.pdf","ECO 102"),
                 Course("Economic Resources","ECO 202","This course focuses on studying the nature, availability, distribution and development of the economic resources. The three main types of economic resources are : Human, capital and natural resources. ","2","https://www.oecd.org/greengrowth/MATERIAL%20RESOURCES,%20PRODUCTIVITY%20AND%20THE%20ENVIRONMENT_key%20findings.pdf","ECO 102"),
                 Course("Foreign Trade Theory","ECO 203","This course deals with trade theories, i.n., the pattern and the gains from us to You of absolute advantage and the law of absolute advantage and the law of comparative advantage and, further,examines the basis and the gain from according to these theories.","2","http://bgc.ac.in/pdf/study-material/International-Trade.pdf","ECO 102"),
                 Course("Public Finance and Taxation","ECO 301","This course covers the main issues related to spending and taxation: activities of government and their influence on the allocation of resources and distribution of income.","3","https://eopcw.com/assets/stores/Public%20Finance%20&%20Taxation/lecturenote_1669791855Public%20Finance%20and%20Taxation%20Accounting.pdf","ECO 102"),
                 Course("Economic Feasibility Studies","ECO 302", "This course focuses on the study of economic and financial appraisal of projects. It provides students with a comprehensive coverage of the different project evaluation methods and financial decision-making techniques. ","3","http://www.pathways.cu.edu.eg/subpages/training_courses/C15-Feasibility-EN.pdf","ECO 102,ACC 202"),
                 Course("Economic Development and Planning","ECO 303","This course covers the main theories of economic growth and development, factors causing economic development, financing of economic development, trade strategies and other factors affecting the economic development.","3","http://www.unishivaji.ac.in/uploads/distedu/extraunts_ba3ecoeng_150313.pdf","ECO 102"),
                 Course("Small Industries Economics","ECO 304","The purpose of this course is to provide students with a comprehensive coverage of the necessary issues related to successfully creating, managing and growing a small business. ","3","https://www.oecd.org/cfe/smes/2090740.pdf","ECO 102"),
                 Course("Foreign Trade Policies","ECO 305","This course deals with the international trade or the commercial policies. It examines tariffs, the most important of trade restrictions historically It extends the discussions to other trade restrictions, evaluate the justification usually given for trade restrictions and summarizes their history. ","1","https://web.worldbank.org/archive/website00894A/WEB/PDF/LEDERMAN.PDF","ECO 203"),
                 Course("Energy Economics","ECO 306","This course aims to provide students with a deep analysis to the role of energy in economy and key aspects of energy supply and demand.","3","https://web.stanford.edu/~jsweeney/paper/Energy%20Economics.PDF","ECO 202"),
                 Course("International Economics Relations","ECO 307","This course is compilation of international economics course of the two courses international trade theory and international trade policies.","3","http://dspace.oneu.edu.ua/jspui/bitstream/123456789/1944/1/An%20Introduction%20to%20International%20Economic%20Relations.pdf","ECO 203"),
                 Course("Global Economic Blocs","ECO 308","This course focuses on the study of economic integration theories and the several economically integrated regional blocs, such as the European Union. ","3","https://www.press.umich.edu/pdf/047209906X-ch1.pdf","ECO 203"),
                 Course("Economic Information Systems","ECO 309","This course aims to provide students with a comprehensive analysis to the role of information in modern economy and the economic aspects of information systems.","3","https://www.econstor.eu/bitstream/10419/102641/1/Information_Systems_and_Economic_Value_Added.pdf","ECO 303") ,
                 Course("International Trade (Problems)","ECO 401","This course studies the nature of the main obstacles affecting the development of international trade relations, and how such problems can be tackled. Both theoretical and practical methods are used in the analysis.","4","https://unctad.org/system/files/non-official-document/cimem5_2014_Thorstensen.pdf","ECO 203"),
                 Course("Egyptian Economic (History)","ECO 402","This course focuses on the exploration of the record of the Egyptian economic growth and change in Egyptian economic institutions from a certain period to another.","4","https://www.oecd.org/countries/egypt/2498037.pdf","ECO 102"),
                 Course("International Marketing","ECO 403","This course covers the basic concepts of the international marketing activity and theory. Topics include: Opportunities, characteristics, and trends in foreign markets as well as strategies, organization and control,and the problems of adapting marketing concept and method to the international settings.","4","https://www.lsms.ac/public/uploads/SumhS6i63Do8WQhnLljLZObn9t0BVri0Ml33fwkUvLthgrGlr61575375905uctMarhSuErhLGwG4DDEg0j6bcabRl3Rp11t5iyCiZlj6GC3QZ.pdf","BUS 201,ECO 203"),
                 Course("History of Economic Thought","ECO 404","This course cover the development of modern thought with attention to the historical order. Individual economists and schools of thought are examined tor historical background, essential ideas and usefulness.","4","https://eclass.uoa.gr/modules/document/file.php/ECON616/E.%20K.%20Hunt%2C%20Mark%20Lautzenheiser%20-%20History%20of%20Economic%20Thought_%20A%20Critical%20Perspective-M.E.%20Sharpe%20%282011%29.pdf","ECO 305"),
                 Course("Contemporary Economic Systems","ECO 405","This course cover study of capitalism and socialism, including theoretical interpretations of these systems. It also compares and evaluates a variety of economic systems with respect to the many factors which directly or indirectly affect economic behaviour and outcomes. ","4","https://www.bu.edu/eci/files/2021/08/Comparative-Economic-Systems.pdf","ECO 303"),
                 Course("Econometrics","ECO 406","This course consists of two parts: The first part focuses on the mathematical economics. Mathematical economics is the use of mathematical tools in economic analysis.The second part of the course emphasize econometrics.","4","https://library.ku.ac.ke/wp-content/downloads/2011/08/Bookboon/Economics/econometrics.pdf","ECO 303,STS 201"),
                 Course("National Accounts","ECO 407","This course aims to provides students with the necessary techniques commonly used in presenting the transactions taking place between different agents in economy in accordance with the system of national accounting (SNA) under different approaches. ","4","https://unstats.un.org/unsd/publication/SeriesF/seriesF_85.pdf","ECO 303"),
                 Course("Contemporary Economic Problems","ECO 408","This course covers the study of selected current economic problems in areas of growth, unemployment, inflation, income distribution, and poverty, and efficiency of resource allocation in the Egyptian economy.","4","http://www.umass.edu/preferen/gintis/human.pdf","ECO 303"),
                 Course("Arab Countries Economics","ECO 409","This course examines the process of economic development in the Arab countries. It is designed to expose students to current thinking by academics and policy-makers on past experiences and future challenges facing the economies of the Arab countries.","4","https://www3.weforum.org/docs/WEF_The_New_Economic_Context_Arab_World_flyers_2017.pdf","ECO 303"),
                 Course("Multinational Corporations","ECO 410","This course covers the development of the multinational enterprise, the determinants of foreign direct investment, the economics of the multinational firm, the impact of multinational corporations on host and home country development, and case studies of the impact of multinationals on the less developed countries. ","4","https://www.brookings.edu/wp-content/uploads/2021/04/GG_Ch1_Summary.pdf","ECO 307"),))
         ,
             Major("Political Science",arrayListOf(Course("Introduction to Law","LAW 101","This course aims to provide the students with the main ideas and principles of law, such as: The definition of law, the elements of the legal rules, its kinds and sources of law . ","1","http://kretschmer.cc/pdf/introduction_1.pdf","NONE") ,
                 Course("Commercial Law","LAW 201","This course cover definition of the commercial law, its theories, bases and sources which constitute the main study in this course. It includes also a number of issues: The commercial contract, principles and kinds of banking operations, and bankruptcy.","2","https://www.wto.org/english/thewto_e/acc_e/vnm_e/wtaccvnm43_leg_11.pdf","LAW 101"),
                 Course("Public International Law","Law 303","The aim of this course is to introduce the public international law to political science students. It covers a number of topics: Definition of the international law, its source; the state from a legal viewpoint; sovereignty, equality of states and recognition.","3","https://prawo.uni.wroc.pl/sites/default/files/students-resources/introduction%20to%20public%20international%20law.pdf","LAW 101,POL 201"),
                 Course("Conflicts & Arbitration","LAW 401","This course explains, first, the public theory of peaceful arrangements for international conflicts. The second section focuses on the difference between political and the legal conflict.","4","https://icsid.worldbank.org/sites/default/files/Background_Papers_Issue_Conflict_Final_2.26.2021.pdf","LAW 303"),
                 Course("Political Science (1)","POL 101","This course deals with a number of topics, such as: The definition of political science and its relation with other social sciences. Theory of the state is dealt with in detail, to some extent; the definition of state and its essential elements, origin as well as forms of the state (united and federal).","1","https://www.hse.ru/data/2018/01/26/1162911138/program-1828008040-waENlZ082g.pdf","NONE"),
                 Course("Introduction to Political Science (2)","POL 201","This course focuses on the comparative political systems and their classifications. Pressure groups are discussed in some detail. To be added is the field of international relations: Meaning of the concept. main factors in international relations, elements of the national power of the state, international system old and new. It casts also light on the history of political thought.","2","https://www.hse.ru/data/2018/01/26/1162911138/program-1828008040-waENlZ082g.pdf","POL 101"),
                 Course("History of Political Thought","POL 301","It is one of the core courses in this field. It trace Western Political thought during successive ages: Ancient Greek, Roman, Christian, Middle Ages, modern as well as the contemporary times.","3","https://scholarcommons.sc.edu/cgi/viewcontent.cgi?referer=&httpsredir=1&article=1018&context=poli_facpub","POL 201"),
                 Course("Theory of Comparative Political Systems","POL 302","This course aims to provide the students with the main ideas in such field. Basic concepts are to be discussed in depth: System, comparative analysis, elements of a political system, and main institutions, formal and informal.","3","https://www.shivajicollege.ac.in/sPanel/uploads/econtent/64f62e627be9f3fa4849dbf539388fe0.pdf","POL 201"),
                 Course("Theory of International Relations","POL 303","Definition of I.R is the starting point in this course. The essential elements of national power of the state are discussed. Classification of states into small, medium, big and super are explained. This course also discusses the representatives in the foreign scene: States, international organizations, multi-national corporations, pressure groups and non- governmental organizations.","3","http://www.e-ir.info/wp-content/uploads/2017/11/International-Relations-Theory-E-IR.pdf","POL 201"),
                 Course("International Organizations","POL 304","This course aims to study the international organizations in general Therefore, it deals with a number of points such as international organization and its development. ","3","https://www.asil.org/sites/default/files/ERG_IO.pdf","POL 201"),
                 Course("International Relations in the 20th Cent","POL 305","This course deals with the diplomatic history of the world. It starts with a hint to international developments in the 17th, 19th centuries. Then it concentrates, in details, on the 20th century, particularly the two major world wars; their causes and effects.","3","https://www.colaisteeanna.ie/wp-content/uploads/2011/01/History-Revision-International-Relations-in-the-20th-century.pdf","POL 201"),
                 Course("Diplomatic and Consular Systems","POL 306","This course explains the meaning and history of diplomacy as a concept and as a career. Theories of diplomatic and consular immunities and privileges are to be discussed as well.","3","https://www.state.gov/wp-content/uploads/2019/07/2018-DipConImm_v5_Web.pdf","POL 201"),
                 Course("Political Theory","POL 307","This course is divided into two basis sections. The first deals with the political values such as liberty, justice, equality, democracy, and power. The other section studies authority as a phenomenon. It includes a number of issues: Essence and content of authority, state functions and its theories, political behaviour, political obligations, as well as elite theory.","3","https://archive.mu.ac.in/myweb_test/M.A.(Part%20-%20I)%20Political%20Science%20Paper%20-%20I%20-%20Political%20Theory%20(Eng)%20-%20Rev.pdf","POL 201"),
                 Course("Egyptian Political Systems","POL 401","Developments in the Egyptian government and politics during the 20th century is the core of this course: constitutions, political life, parliaments, the three main powers: the Legislative, Executive, and Judicial, before and after the 1952 Revolution.","4","https://carnegieendowment.org/files/CP305_Dunne_and_Hamzawy_Parties_Final_Web.pdf","POL 302"),
                 Course("Comparative Political Systems","POL 402","This course deals with some examples of contemporary political systems. It is divided into two 'main parts: The first studies the developed political systems such as the U.S.A., the U.K., some nations in Asia and Africa such as China, India, and Nigeria.","4","https://gavsispanel.gelisim.edu.tr/Document/ycilliler/20190218092030868_829a7f14-9e76-4f4f-815d-b3f6f81288a9.pdf","POL 302"),
                 Course("Political Development","POL 403","Definition of political development is the starting point in this course. The following points include: Japanese, agents of development, crisis of development, and clash of civilizations. ","4","https://faculty.georgetown.edu/brumberg/govt778.pdf","POL 302"),
                 Course("Foreign Policies of Major Powers","POL 404","This course is designed to such countries in order to acquire power, influence and hegemony. A special attention is to be given to the policies of such powers towards the Arab World and the Middle East as well.","4","https://www.press.umich.edu/pdf/0472112872-ch2.pdf","POL 305"),
                 Course("Political Problems in the Arab World","POL 405","The focus of this course is the analysis of a number of the most important problems in the Arab region such as: Development, democracy, and human rights.","4","https://core.ac.uk/download/pdf/19578257.pdf","POL 305"),
                 Course("Contemporary Issues in World Politics","POL 406","This course deals with a number of the most important contemporary issues in the global arena. International crisis: theory and examples, globalization, new world order, and human rights are to be examined.","4","https://archive.mu.ac.in/myweb_test/TYBA%20study%20material/T.Y.B.A.%20Politics%20Paper%20-%20VI%20-Major%20issues%20in%20Contemporary%20Politics%20-%20Eng.pdf","POL 305"),
                 Course("Regional Organizations","POL 407","Topics included in this course are: theory of regionalism, relation between regional security and stability. Three regional organizations are thoroughly discussed, namely: the League of Arab States, the former Organization of African Unity (OAU), and the Organization of Islamic Conference regional arrangements such as OAS, ASEAN, APEC, and SARC.","4","https://reliefweb.int/sites/reliefweb.int/files/resources/1095455460.pdf","POL 304"),
                 Course("Egyptian Foreign Policy","POL 408","This Course deals with two major parts: First, the essential factors, geo strategic, which formulate the Egyptian political behaviour in the foreign science, such as the geographical location, population , armed forces and leadership. The other part concentrates on the circles of the Egyptian foreign policy: Arab, African, Islamic, and developing countries. Egyptian foreign policy towards the major powers: the USA, the UK.","4","https://eprints.ucm.es/id/eprint/47417/1/T39878.pdf","POL 305"))))

         ), Faculty(" Medicine",R.drawable.medicine, arrayListOf(
             Major("",
                 arrayListOf())
         )), Faculty("Dentistry",R.drawable.dentisry, arrayListOf(
             Major("",
                 arrayListOf())
         )), Faculty("Pharmacy",R.drawable.pharmacy, arrayListOf(
             Major("",
                 arrayListOf())
         )),Faculty("Physical Therapy",R.drawable.physicaltherapy, arrayListOf(
             Major("",
                 arrayListOf())
         )),Faculty("Biotechnology",R.drawable.biotechnology, arrayListOf(
             Major("",
                 arrayListOf())
         )),Faculty("Mass communication",R.drawable.mass, arrayListOf(
             Major("",
                 arrayListOf())
         )),Faculty("Foreign Languages",R.drawable.foregin, arrayListOf(
             Major("",
                 arrayListOf())
         )),Faculty("IT",R.drawable.computersciemce, arrayListOf(
             Major("",
                 arrayListOf())
         )),Faculty("Applied Medical Sciences",R.drawable.applied, arrayListOf(
             Major("",
                 arrayListOf())
         )),Faculty("Archeology and Tourist Guidance",R.drawable.tourist, arrayListOf(
             Major("",
                 arrayListOf())
         )),Faculty("Special Education",R.drawable.specialeducation, arrayListOf(
             Major("",
                 arrayListOf())
         )),Faculty("Engineering",R.drawable.engineer, arrayListOf(
             Major("",
                 arrayListOf())
         ))
         )
        adapter = FacultiesAdapter(faculties){ getSelectedIndex(it)}
        recyclerView.adapter = adapter
        recyclerView.layoutManager = GridLayoutManager(this,2)
        adapter.notifyDataSetChanged()
    }
    fun getSelectedIndex(index:Int){
        majorsIntent = Intent(this, MajorsActivity::class.java)
        majorsIntent.putExtra(Constants.major,faculties[index].majors)
        startActivity(majorsIntent)
    }
}